
version: "3.7"
services:
  app:
    build:
      args:
        user: info
        uid: 1001
      context: ./
      dockerfile: Dockerfile
    image: laravel-image
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - mibsoft

  db:
    image: 'mysql:8.0'
    container_name: mibsoft-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'mibsoft'
      MYSQL_ROOT_PASSWORD:  'root'
      MYSQL_PASSWORD: 'lifesucks@321'
      MYSQL_USER: 'mib'
      SERVICE_TAGS: devdb
      SERVICE_NAME: mysql
    volumes:
      - /var/data/mysql:/var/lib/mysql
      - /etc/mysql:/etc/mysql
      - ./mysql-files:/var/lib/mysql-files
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    networks:
      - mibsoft

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - mibsoft

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - mibsoft

networks:
  mibsoft:
    driver: bridge
